### ISSUE TITLE
1.52 Sybaris NullReferenceException Error

### ISSUE THREAD

**Issue by ghost** [denikson/CM3D2.YATranslator#1]
Hi,

I decided to hop on your new project.
There were no errors when building.
I cleaned up the old TranslationPlus and put YAT, no errors when loading plugin

Unfortunately translations don't load, there are errors with every new scene loading.

I'm using 4.2 UI translation files and system text translation v. 07/31/17

I'm available if you need anything to test out or need more info/data.
(of course if all this is because I messed up something, then sorry for trouble)

![debug](https://user-images.githubusercontent.com/30577638/29004823-7ca8c1d2-7ace-11e7-86d2-cfd64ececfe1.png)
![debug2](https://user-images.githubusercontent.com/30577638/29004821-7c9f1ad8-7ace-11e7-95e7-97b268ea2a24.png)
![debug3](https://user-images.githubusercontent.com/30577638/29004824-7ca9b6a0-7ace-11e7-9c50-bab8f896bbd4.png)
![debug4](https://user-images.githubusercontent.com/30577638/29004822-7ca5b690-7ace-11e7-9016-dbb73ef8d188.png)

**Comment by ghorsington** [comment]
Greetings!

Thank you for reporting this one. 

Since the wiki isn't yet ready, here's a brief explanation:
It's most likely due to Sybaris failing to apply the patcher.
Unfortunately Sybaris doesn't natively provide a means to log these problems properly.
However, there is a solution: a custom-made Sybaris.Loader.

Download this:
[Sybaris.Loader_Custom.zip](https://github.com/denikson/CM3D2.YATranslator/files/1203210/Sybaris.Loader_Custom.zip)

Put the DLL into `Sybaris\Loader` folder. **Back up** the DLL you currently have there before replacing!
After that, run CM3D2. After the game has launched, you should see these two files in your **CM3D2 root** directory (where CM3D2x86/64.exe is located):

* Sybaris_patch.log (contains the patching log)
* Assembly-CSharp.patched.dll (contains the patched Assembly-CSharp which Sybaris keeps in computer memory)

Copy the contents of `Sybaris_patch.log` here. It should contain information about the patching error.

**Comment by ghost** [comment]
[Sybaris_patch.txt](https://github.com/denikson/CM3D2.YATranslator/files/1203217/Sybaris_patch.txt)

**Comment by ghorsington** [comment]
It seems that your Cecil.Inject might be outdated.

Make sure you actually have **the latest** [Cecil.Inject](https://github.com/denikson/Mono.Cecil.Inject/releases) installed in your `Loader` folder. 
Make also sure to build with the latest version of it (or use the prebuilt release).


Or you could build YAT with the same version of Cecil.Inject that you have in your `Loader` folder.

**Comment by ghost** [comment]
Ok, now it works.

I'm sorry for wasting your time.

**Comment by ghorsington** [comment]
It's fine.

That's why I'm here.


This just reminds me to include this into the FAQs.
