### ISSUE TITLE
Make a separate version for Sybaris 2.0

### ISSUE THREAD

**Issue by Raimoo** [denikson/CM3D2.YATranslator#17]
Would it be better to make a separate version for Sybaris2.0?

I know it's the same Sybaris but Sybaris for CM3D2 works differently with Sybaris 2.0 and since that version remains working for CM3D2, I prefer not to disturb it.

**Comment by ghorsington** [comment]
Greetings! Thank you for the suggestion.

The main difference between both Sybaris versions is the location of the `Hook` DLL. While usually you could put it into either `Sybaris/Plugin/Managed` or `Sybaris/Loader` alongside the patcher DLL. In new version of Sybaris, **only the latter version is supported**. 

Since the change is small and doesn't break compatibility between different Sybaris versions, there is simply no need for a separate version.

Thus note that starting with **YAT 1.5.0.0**, if you use Sybaris, you will have to put `CM3D2.YATranslator.Hook.dll` **in the same folder as `CM3D2.YATranslator.Sybaris.Patcher.dll`. In other words if you use

* Sybaris 1.0, put `CM3D2.YATranslator.Hook.dll` into `Sybaris/Loader`
* Sybaris 2.0+, put `CM3D2.YATranslator.Hook.dll` into `Sybaris`.

The change is also specified in the README and the CHANGELOG of 1.5.0.0.
