### ISSUE TITLE
YATranslator Version 1.5.1.0 error - COM3D2 1.07.0 , Sybaris2.1 

### ISSUE THREAD

**Issue by holy1017** [denikson/CM3D2.YATranslator#18]
YATranslator Version 1.5.1.0 error - 
COM3D2 1.07.0 , 
Sybaris2.1 

https://youtu.be/ox2zQS1Y4yI
02:14 view plz

**Comment by ghorsington** [comment]
This is a known issue. To implement proper string reloading requested in #8, YAT was changed to append an invisible character to every single string that was attempted to be translated. That was done to allow for faster translation. 

However, some of UI in the game is programmed to *use the UI text* to decide the logic. That is indeed the case with Studio Mode UI -- poorly written UI logic broke as soon as YAT added a small invisible character to the UI strings.

This issue is now fixed by reverting some of the changes done for #8.

As a side note, `EnableStringReload` is only meant for translators. This is because enabling string reloading makes translation process slower. For normal users, please keep `EnableStringReload` set to `False`.
