### ISSUE TITLE
Issue with clipboard and text doubles.

### ISSUE THREAD

**Issue by ShinRaikdou** [denikson/CM3D2.YATranslator#19]
Apparently YAT always copy both strings to clipboard. Because of this 3rd party translation programs are messed up and text hard to read.
Can it be fixed or I do something wrong?
Here example https://i.imgur.com/789TYwt.png

**Comment by ghorsington** [comment]
Greetings! Pardon the prolonged wait for such a minor fix -- [some other projects](https://i.imgur.com/rrEN603.png) are taking their own time.

The issue was a minor one and caused by YAT itself -- it passed those pesky template strings (the ones with `[HF]` and `[SF]`). Since they are not what you most likely want, YAT will now only copy final strings (with all names inserted).
