### ISSUE TITLE
YAT somehow cause the haversting feature in VPVR to not work

### ISSUE THREAD

**Issue by ghost** [denikson/CM3D2.YATranslator#2]
Well, apparently, I tried to run the harvesting feature in VPVR by try to plant a seed, but after the dialogs, nothing happens.

- I can still see the "植物を植える" cursor when focusing on the garden sign, when that is not suppose to happen.
- even after I proceed to the next in-game day, the plant didn't show up as it suppose to be
- checking the console, it gave this error

```畑の種]植物「にんじん」は存在しない
NullReferenceException: Object reference not set to an instance of an object
```

**Comment by ghorsington** [comment]
The problem was partially on YAT's and partially on CM3D2's side.

For some reason CM3D2 devs decided to use cultivation UI's buttons' labels (the text) as a key to the whole button and the event invoked by the button itself.

Since YAT simply replaces the text with the translation thereof, the cultivation UI fails to find the button (because again, the button is indexed by the **label text**).

Since there is no way around it, I fixed it temporarily by redirecting the whole button finding method to YAT's side. While it works, it will be prone to break in future updates until CM3D2 fix their cultivation UI on their part.
