### ISSUE TITLE
Method not found: "UnityInjector.PluginBase.get_Preferences"

### ISSUE THREAD

**Issue by ghost** [denikson/CM3D2.YATranslator#24]
Im having a problem getting the Plugin to run, with the shown errors in the picture.
Is it possible to get YAT to run with Bepinex? If not, then this issue is obsolete, sorry for that.

I have installed the most recent versions of the YAT and IMGUI plugins as well as CecilInject.
![unbenannt](https://user-images.githubusercontent.com/41988103/43509428-f2e17fbe-9572-11e8-8bf4-2f330312461f.jpg)

**Comment by ghorsington** [comment]
Greetings!

It sure is possible. Make sure you have the latest version of BepInEx with ports of SybarisLoader and UnityInjector installed. Moreover, you have to make sure to migrate your Sybaris installation properly.

Instead of doing it all manually, I suggest using [COM3D2 Sybaris 2 to BepInEx migration AIO](https://github.com/NeighTools/COM3D2.BepInEx.AIO/releases) I maintain. Just follow the README included in it and it will do all the migration work cleanly.

After that, update your game (the latest version is 1.18 as of the time of me writing this) and reinstall YAT (install it just like you normally do with Sybaris).

**Comment by ghost** [comment]
Greetings and thanks for the answer.

After testing a bit with the AIO package, i've managed to get it working. The problem seems to be an incompability between YAT and the XUnity Auto Translator i've also had installed(should have mentioned that earlier).
So it seems one has to choose between translated buttons and translated texts while the autotranslater for sybaris is broken.
Any idea how one could get those to working together?

Thanks in advance!

**Comment by ghorsington** [comment]
The problem is that the XUnity's AT uses ExIni, but UnityInjectorLoader contains its own custom version of it.

Try installing [the new version of UnityInjectorLoader](https://github.com/BepInEx/BepInEx.UnityInjectorLoader/releases/download/v1.2.0.0/BepInEx.UnityInjectorLoader.zip). Just extract the zip into `BepInEx` folder.

It seems to work, but as long as you build from source yourself. Here's a version I built from [Vimek/XUnity.AutoTranslator](https://github.com/Vimek/XUnity.AutoTranslator) (the version has GoogleTranslateHack endpoint that works -- just set `Endpoint=GoogleTranslateHack` in `BepInEx/AutoTranslatorConfig.ini` after you have run the game once):

[XUnity.AutoTranslator.Plugin.BepIn.zip](https://github.com/denikson/CM3D2.YATranslator/files/2249224/XUnity.AutoTranslator.Plugin.BepIn.zip)

**Comment by ghost** [comment]
Worked lika a charm, thanks a lot!
