### ISSUE TITLE
Compatibility with GripMovePlugin

### ISSUE THREAD

**Issue by Advent-Seph** [denikson/CM3D2.YATranslator#7]
*Edit: Fixed links*

Sorry about that, meant to respond a lot sooner but got really busy recently. I took screenshots of most of the immediately visible issues, got the debug log, and also copied over my assets in case that helps: https://mega.nz/#!bZ0BzSgD!XS3s0FBbalAEWYyX6VoieF0DwN5B9NLrK0tqv7c4dlA

I'm using the default .bat file (CM3D2x64_VR.bat) included in CM3D2 to run VR.

Other Info:
YAT version I tested with: 1.3.2.1
CM3D2 Version: 1.53 x64
VR Headset: Oculus Rift CV1 firmware 708/34a904e8da
OS: Windows 10 Home x64
Sybaris build: 160930

[debug for 1.3.2.1.log](https://github.com/denikson/CM3D2.YATranslator/files/1544774/debug.for.1.3.2.1.log)

[debug for 1.4.log](https://github.com/denikson/CM3D2.YATranslator/files/1544776/debug.for.1.4.log)

**Comment by ghorsington** [comment]
Thank you for the extensive information! I'll test the assets as soon as I can.

That said, could you repost the log with verbosity enabled? That is, set [`Verbosity`](https://github.com/denikson/CM3D2.YATranslator/wiki/Configuration#verbosity) to `Assets|Textures` and go to the Load Game UI (or any UI that looks broken).

In addition, are you using any locale emulators? If you do, which one?

**Comment by Advent-Seph** [comment]
[debug.log](https://github.com/denikson/CM3D2.YATranslator/files/1545306/debug.log)

I've updated to YAT 1.4 now but aside from that everything else in the scenario was the same. I went to all the same parts of the game as I did for the other two debug logs.

I did use NTLEA back when I first started using CM3D2 but that was with ReiPatcher. When I switched to Sybaris I did a clean install and just set my system locale to Japanese now. (via the control panel)

**Comment by ghorsington** [comment]
Your `AtlasCommon` asset is outdated, which causes the issue. You do have two updated versions named as `1367BD762E26A742` and `4209AC888C3D23D8`, so renaming either one to `AtlasCommon` should work.

That said, there is an issue with loading of translated textures. Going to make a separate issue for that.

EDIT: Moved to issue #9 .

**Comment by Advent-Seph** [comment]
I'm not so sure about `AtlasCommon` being outdated. YAT dumps it when dumping assets, and I double checked by scribbling it with red lines to see if anything messed up in-game and I could only find it had affected the Gallery Night Service section.

But to be thorough I double-checked with every possible scenario:

Deleting `AtlasCommon`  only
Deleting `AtlasCommon` and replacing it with the renamed `1367BD762E26A742`
Deleting `AtlasCommon` and replacing it with the renamed `4209AC888C3D23D8`
Renaming `AtlasCommon` into `10C5BF1DD3744404@14`

Deleting `AtlasCommon` didn't change anything, assets were still broken in vr. Trying to replace it with a renamed `1367BD762E26A742` fixed most of the asset issues but broke the background of the Gallery Night Service. Renaming `4209AC888C3D23D8` also broke the Gallery Night Service but it also mislabeled certain buttons (like changing `Edit Player` into `Night Service`)

Renaming the original AtlasCommon I have into `10C5BF1DD3744404@14` completely fixed the issue. I tested it in VR and regularly, with and without GripMovePlugin and the assets load fine now. (though, when i'm in the Gallery Night Service this one error comes up now but doesn't affect the game in any noticeable way: `NullReferenceException: Object reference not set to an instance of an object`)

I logged every change and went straight into the gallery night service only, in order to confirm this.
[debug for 1367BD762E26A742.log](https://github.com/denikson/CM3D2.YATranslator/files/1546891/debug.for.1367BD762E26A742.log)
[debug for 4209AC888C3D23D8.log](https://github.com/denikson/CM3D2.YATranslator/files/1546894/debug.for.4209AC888C3D23D8.log)
[debug for 10C5BF1DD3744404@14 (Regular).log](https://github.com/denikson/CM3D2.YATranslator/files/1546895/debug.for.10C5BF1DD3744404.14.Regular.log)
[debug for 10C5BF1DD3744404@14 (VR).log](https://github.com/denikson/CM3D2.YATranslator/files/1546896/debug.for.10C5BF1DD3744404.14.VR.log)
[No GMP debug for 10C5BF1DD3744404@14 (Regular).log](https://github.com/denikson/CM3D2.YATranslator/files/1546897/No.GMP.debug.for.10C5BF1DD3744404.14.Regular.log)
[No GMP debug for 10C5BF1DD3744404@14 (VR).log](https://github.com/denikson/CM3D2.YATranslator/files/1546899/No.GMP.debug.for.10C5BF1DD3744404.14.VR.log)

And I also took screenshots here and there in case they might be useful: https://mega.nz/#!idlSVBZA!WYk6DDWX6TPRBeTV8ZBZRVOt21aO_L5B7Y1elzQUwvc

I'm not quite sure why this happens. But that's everything I could find when running YAT with GMP in Oculus VR. Sorry if it's a lot of excessive info, figured it'd be better to be overprepared than not.

**Comment by ghorsington** [comment]
Ah, I see now! The `AtlasCommon` is different from scene to scene, which can cause some issues.
You should create two copies of `1367BD762E26A742` and rename them to `32CDB08E1B9E7490@8` and `4209AC888C3D23D8`.
In addition, remove `AtlasCommon` and `10C5BF1DD3744404@14`, since the former **is** outdated and the latter is a texture for a font, not an atlas. If you have any other excess versions of `AtlasCommon`, remove them too (sans the three aforementioned ones).
That way you should only have the following versions of `AtlasCommon`:
```
1367BD762E26A742.png
32CDB08E1B9E7490@8.png
4209AC888C3D23D8.png
```

Moreover, I suggest getting Assets folder from a pre-made translation pack. For instance the [AIOUE](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/custom-maid-3d-2-mods/5816208-sybaris-aio-ultimate-english-expansion-1-53-1-beta-suggestions-are-welcome) should contain a working `Assets` folder. You can just replace the one you had.
If I recall correctly, you will also need the new [`AtlasCommon2.png`](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/custom-maid-3d-2-mods/414082-custom-maid-3d-2-english-ui-release-4-2?p=5825775#post5825775) if you get the assets from AIOUE.

Still going to keep this closed, since the solution for the issue has been posted: you need to remove and rename the assets. Using plain names like `AtlasCommon` may mess with texture loading, since the game can use different textures with the same name depending on the level. Either name the textures by their hash value or by tagging them by level with `@` postfix, like `AtlasCommon@14`.
The solution is temporary: the main problem is reported as #9 and will be fixed in future versions of YAT.

**Comment by Advent-Seph** [comment]
Yup, just confirmed making a copy of `1367BD762E26A742` and renaming it `32CDB08E1B9E7490@8` completely fixes all asset issues in Rift VR with GripMovePlugin installed.

I deleted `AtlasCommon` and `10C5BF1DD3744404@14` then downloaded the AIOUE pack to compare with my assets to make sure everything was proper.

Two things I wanna mention tho: AIOUE now has the updated `AtlasCommon2.png`, no worries there. Also, copying `1367BD762E26A742` and renaming it `4209AC888C3D23D8` would probably be ill-advised as even the AIOUE version of `4209AC888C3D23D8` has buttons with different labels from `1367BD762E26A742` and making them duplicates would result in mismatched buttons in-game.

But yo, thanks a million for this, mate. I'm still not quite sure why UTP & Translation+ didn't act up from a missing `32CDB08E1B9E7490@8` and outdated `AtlasCommon`. But hey, this is definitely fixed now so i'm not complaining.

**Comment by ghorsington** [comment]
You're quite welcome! As I mentioned, the core problem is a bug in YAT's asset translation; this is now reported as #9 . It will be fixed soon, but until that you will have to make do with this weird renaming. Sorry about that.
